### ISSUE TITLE
Can't access the enums in the definition of colorSensor class for java for the configuration of the ir sensor leds.

### ISSUE THREAD

**Issue by john-doe-blip** [REVrobotics/Color-Sensor-v3#5] opened 2020-01-18 02:02 UTC
The enums aren't public and they are only visible in the package.

**Comment by willtoth** [comment] 2020-01-18 02:06
This is a duplicate of https://github.com/REVrobotics/Color-Sensor-v3/issues/3 and is already addressed. We'll have a build out soon with this fix.

**Closed by willtoth** 2020-01-18 02:06 UTC
